INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Angela'  , 'Peterson'  , '1984-09-12', 'angela@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Bruce'   , 'Bellamy'   , '1989-02-24', 'bruce@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Craig'   , 'Simpson'   , '1978-03-26', 'craig@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Daniel'  , 'Smith'     , '1976-04-18', 'daniel@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Emily'   , 'Zimmermann', '1982-05-08', 'emily@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Frank'   , 'Rikard'    , '1981-06-10', 'frank@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Gabriel' , 'Torres'    , '1983-07-02', 'gabriel@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Henry'   , 'Smith'     , '1992-08-28', 'henry@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Ivy'     , 'Smith'     , '1997-09-04', 'ivy@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'John'    , 'English'   , '1994-10-06', 'john@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Kenny'   , 'Smith'     , '1995-11-22', 'kenny@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Leonardo', 'Lorenzo'   , '1998-12-20', 'leonardo@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Mandy'   , 'Moore'     , '1987-02-06', 'mandy@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Nils'    , 'Robertson' , '1988-01-14', 'nils@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Orlando' , 'Bloom'     , '2000-01-16', 'orlando@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Peter'   , 'Alvaro'    , '1999-03-18', 'peter@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Quinlan' , 'Smith'     , '1996-04-12', 'quinlan@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Richard' , 'Smith'     , '1985-05-10', 'richard@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Steve'   , 'Ballmer'   , '1987-06-20', 'steve@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Thomas'  , 'Smith'     , '1989-07-22', 'thomas@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Ullrich' , 'Smith'     , '1991-08-26', 'ulrich@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Wesley'  , 'Schneider' , '1992-09-30', 'wesley@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Xavier'  , 'Smith'     , '1985-10-31', 'xavier@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Yoda'    , 'Spezies'   , '1994-11-30', 'yoda@example.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Zach'    , 'Efron'     , '1997-12-26', 'zach@example.com');