INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mr.' , 'Angela'  , 'Peterson'  , '1984-09-12', 'john@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Bruce'   , 'Bellamy'   , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Craig'   , 'Simpson'   , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Daniel'  , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Emily'   , 'Zimmermann', '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Frank'   , 'Rikard'    , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Gabriel' , 'Torres'    , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Henry'   , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Ivy'     , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'John'    , 'English'   , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Kenny'   , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Leonardo', 'Lorenzo'   , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Mandy'   , 'Moore'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Nils'    , 'Robertson' , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Orlando' , 'Bloom'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Peter'   , 'Alvaro'    , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Quinlan' , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Richard' , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Steve'   , 'Ballmer'   , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Thomas'  , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Ullrich' , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Wesley'  , 'Schneider' , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Xavier'  , 'Smith'     , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Yoda'    , 'Spezies'   , '1989-02-12', 'jane@smith.com');
INSERT INTO CUSTOMER (TITLE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL) VALUES ('Mrs.', 'Zach'    , 'Efron'     , '1989-02-12', 'jane@smith.com');